version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itfreelance_php
    volumes:
      - ./:/var/www/html
    expose:
      - '9000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: itfreelance
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  nginx:
    image: nginx:alpine
    container_name: itfreelance_nginx
    ports:
      - '8081:80'  # Изменён порт с 8080 на 8081
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: postgres:15-alpine
    container_name: itfreelance_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itfreelance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Порт PostgreSQL можно не пробрасывать наружу, если не нужен доступ с хоста
    # ports:
    #   - '5432:5432'

volumes:
  postgres_data: